server:
  port: 8080

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/caojx-git/spring-cloud-config-repo
          #git仓库账号
          username: 389715062@qq.com
          #git仓库密码
          password: Github389175062
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG


